---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
  skip:
    - mypy # Uses language: system, not available in pre-commit.ci sandbox
    - protolint-docker # Needs Docker, not available in pre-commit.ci
    - hadolint-docker # Needs Docker, not available in pre-commit.ci
  autofix_prs: true
  autoupdate_schedule: monthly

# Force all unspecified python hooks to run python 3.10
default_language_version:
  python: python3.10
default_stages:
  - commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude_types:
          - "markdown"
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--unsafe]
      - id: check-added-large-files
        args: ["--maxkb=15240"]
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-ast
      - id: check-json
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: debug-statements
      - id: detect-private-key
      # - id: detect-aws-credentials
      #   args: ["--allow-missing-credentials"]
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      # - id: fix-encoding-pragma
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # - id: double-quote-string-fixer
      # - id: name-tests-test
      - id: no-commit-to-branch
        args: [--branch, main]
      # - id: requirements-txt-fixer
      # - id: file-contents-sorter
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [--config=pyproject.toml]
  # - id: black
  #   alias: black-check
  #   stages: [manual]
  #   args:
  #   - "--check"
  #   - "--diff"
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/tox-dev/tox-ini-fmt
    rev: "1.3.1"
    hooks:
      - id: tox-ini-fmt

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        entry: pyupgrade --py39-plus --keep-runtime-typing
        types:
          - python
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.4.0
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: "\\.(py)$"
        args: [--settings-path=pyproject.toml]
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=120]
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.3.0
  #   hooks:
  #     - id: mypy
  #       args:
  #         [
  #           --show-error-codes,
  #           --pretty,
  #           --ignore-missing-imports,
  #           --check-untyped-defs,
  #           --implicit-reexport,
  #           --python-version=3.8,
  #           --strict,
  #           --warn-unreachable,
  #           --warn-return-any,
  #           --warn-unused-configs,
  #         ]
  #       # files: visitran
  #       language: system
  #       exclude: tests/unit/data/|cloud/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        args: ["--config-file", ".mypy.ini"]
        # files: visitran
        language: system
        types: [python]
        exclude: tests/unit/data/|cloud/|ci/
  - repo: https://github.com/yoheimuta/protolint
    rev: v0.47.5
    hooks:
      - id: protolint-docker
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
  # - repo: https://github.com/pre-commit/mirrors-eslint
  #   rev: "v9.0.0-alpha.2" # Use the sha / tag you want to point at
  #   hooks:
  #     - id: eslint
  #       args: []
  #       files: \.[jt]sx?$ # *.js, *.jsx, *.ts and *.tsx
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@8.41.0
  #         - eslint-config-google@0.14.0
  #         - eslint-config-prettier@8.8.0
  #         - eslint-plugin-prettier@4.2.1
  #         - eslint-plugin-react@7.32.2
  #         - eslint-plugin-import@2.25.2
  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: htmlhint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
    - id: markdownlint
      args: ["--config", "markdownlint.yaml"]
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.34.0
    hooks:
      - id: yamllint
        args: ["--config-file", "yamllint.yaml"]
  - repo: https://github.com/rhysd/actionlint
    rev: v1.6.26
    hooks:
      - id: actionlint
        args: ["--config-file", "actionlint.yaml"]
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker
        args:
          - --ignore=DL3003
          - --ignore=DL3008
          - --ignore=DL3013
          - --ignore=DL3018
          - --ignore=SC1091
        files: Dockerfile$
